https://www.tutorialspoint.com/numpy/index.htm

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

## NumPy - Ndarray Object

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

object: Any object exposing the array interface method returns an array, or any (nested) sequence.	
dtype: Desired data type of array, optional	
copy: Optional. By default (true), the object is copied	
order: C (row major) or F (column major) or A (any) (default)
subok: By default, returned array forced to be a base class array. If true, sub-classes passed through
ndmin: Specifies minimum dimensions of resultant array

In [2]:
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
print(a)

[[1 2]
 [3 4]]


In [4]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


## NumPy - Data Types

Data Types & Description

- bool_: Boolean (True or False) stored as a byte
- int_: Default integer type (same as C long; normally either int64 or int32)
- intc: Identical to C int (normally int32 or int64)
- intp: Integer used for indexing (same as C ssize_t; normally either int32 or int64)
- int8: Byte (-128 to 127)
- int16: Integer (-32768 to 32767)
- int32: Integer (-2147483648 to 2147483647)
- int64: Integer (-9223372036854775808 to 9223372036854775807)
- uint8: Unsigned integer (0 to 255)
- uint16: Unsigned integer (0 to 65535)
- uint32: Unsigned integer (0 to 4294967295)
- uint64: Unsigned integer (0 to 18446744073709551615)
- float_: Shorthand for float64
- float16: Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
- float32: Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
- float64: Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
- complex_: Shorthand for complex128
- complex64: Complex number, represented by two 32-bit floats (real and imaginary components)
- complex128: Complex number, represented by two 64-bit floats (real and imaginary components)

In [6]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

int32


In [8]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)

[('age', 'i1')]


In [9]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [10]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

[10 20 30]


## NumPy - Array Attributes

ndarray.shape: returns a tuple consisting of array dimensions. 

In [12]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


In [13]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


#### ndarray.ndim
returns the number of array dimensions.

In [16]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
print(a.ndim)

# now reshape it 
b = a.reshape(2,4,3) 
print(b)
# b is having three dimensions

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### NumPy - Array From Existing Data

#### numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters.
numpy.asarray(a, dtype = None, order = None)

a: Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists
dtype: By default, the data type of input data is applied to the resultant ndarray
order: C (row major) or F (column major). C is default

In [17]:
# dtype is float 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
print(a)

[1. 2. 3.]


In [18]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print(a)

[1 2 3]


## NumPy - Indexing & Slicing

Contents of ndarray object can be accessed and modified by indexing or slicing
Three types of indexing methods are available − field access, basic slicing and advanced indexing.
A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function.

In [3]:
import numpy as np 
a = np.arange(10) 
print(a)
s = slice(2,7,2) 
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.

In [4]:
import numpy as np 
a = np.arange(10) 
print(a)
b = a[2:7:2] 
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [5]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print(a[2:])

[2 3 4 5 6 7 8 9]


In [6]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
print(a[2:5])

[2 3 4]


In [8]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)

# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [9]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:')
print(a)
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:' )
print(a[...,1] )
print('\n' )

# Now we will slice all items from the second row 
print ('The items in the second row are:' )
print (a[1,...]) 
print ('\n'  )

# Now we will slice all items from column 1 onwards 
print ('The items column 1 onwards are:' )
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


## NumPy - Advanced Indexing
Advanced indexing always returns a copy of the data. As against this, the slicing only presents a view.

There are two types of advanced indexing − Integer and Boolean.
### Integer Indexing


In [10]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


y = x[rows,cols]
[0,1,2]: row1, row2, row3
[0,1,0]:
The selection includes elements at (0,0), (1,1) and (2,0) from the first array.

In [12]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:' )
print(x )
print('\n' )

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:' )
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [14]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:' )
print(x )
print('\n')

rows = np.array([[1,0],[2,3]])
cols = np.array([[1,1],[0,2]]) 

print(rows)

y = x[rows,cols] 
   
print('The corner elements of this array are:' )
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[1 0]
 [2 3]]
The corner elements of this array are:
[[ 4  1]
 [ 6 11]]


The row, column indices of selection are [1, 1] , [0,1], [2,0] and [3,2].

In [17]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:')
print (x )
print ('\n'  )

# slicing 
z = x[1:4,1:3] 

print ('After slicing, our array becomes:' )
print (z )
print ('\n'  )

# using advanced index for column 
y1 = x[1:4,[0,1]] 
y2 = x[1:4,[1,2]] 
print ('Slicing using advanced index for column:' )
print (y1)
print ('=======')
print (y2)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 3  4]
 [ 6  7]
 [ 9 10]]
[[ 4  5]
 [ 7  8]
 [10 11]]


### Boolean Array Indexing
items greater than 5 are returned as a result of Boolean indexing.

In [18]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:') 
print(x) 

# Now we will print the items greater than 5 
print('The items greater than 5 are:' )
print(x[x > 5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The items greater than 5 are:
[ 6  7  8  9 10 11]


Ex2: In this example, NaN (Not a Number) elements are omitted by using ~ (complement operator).

In [20]:
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


Ex3: The following example shows how to filter out the non-complex elements from an array.

In [21]:
import numpy as np 
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


## NumPy - Broadcasting
broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations

In [22]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


Broadcasting is possible if the following rules are satisfied 
- Array with smaller ndim than the other is prepended with '1' in its shape.
- Size in each dimension of the output shape is maximum of the input sizes in that dimension.
- An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
- If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true −
- Arrays have exactly the same shape.
- Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
- Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.

In [23]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print(a)
print('\n')  
   
print('Second array:')
print(b)
print('\n')  
   
print('First Array + Second Array')
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
