Date: 2018/10/20
### Numpy Array
An array can be used to contain values of a data object in an experiment or simulation step, pixels of an image, or a signal recored by a measurement device.

In [2]:
import numpy as np
p = np.array([48.858, 2.294495])
print(p)

[48.858     2.294495]


In [3]:
print(p.ndim) ## getting dimension of array p
print(p.shape) ## getting size of each array dimension
print(len(p))  ## getting dimension length of array p
print(p.dtype) # getting data type of array p

1
(2,)
2
float64


### Data types
There are  ve basic numerical types including Booleans (bool), integers (int), unsigned integers (uint),  oating point (float), and complex. 

### Array creation
- empty, empty_like: Create a new array of the given shape and type, without initializing elements
- eye, identity: Create a NxN identity matrix with ones on the diagonal and zero elsewhere
- ones, ones_like: Create a new array with the given shape and type, filled with 1s for all elements
- zeros, zeros_like
- arange: Create an array with even spaced values in a given interval
- full, full_ like: Create a new array with the given shape and type, filled with a selected value
- array: Create an array from the existing data
- asarray: Convert the input to an array
- copy: Return an array copy of the given object
- fromstring: Create 1-D array from a string or text

### Indexing and slicing

In [4]:
a = np.arange(7)

In [5]:
print(a)

[0 1 2 3 4 5 6]


In [6]:
print(a[1], a [4], a[-1])

1 4 6


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0, 2])

3


In [8]:
c = a[:2]

In [9]:
print(c)

[[1 2 3]
 [4 5 6]]


### Fancy indexing
Besides indexing with slices, NumPy also supports indexing with Boolean or integer arrays (masks). 

In [10]:
a = np.array([3, 5, 1, 10])
b = (a % 5 == 0)

In [11]:
print(b)

[False  True False  True]


In [12]:
c = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])

In [13]:
print(c[b])

[[2 3]
 [6 7]]


### Array functions

In [15]:
a = np.array([[0, 5, 10], [20, 25, 30]])
a.reshape(3,2)

array([[ 0,  5],
       [10, 20],
       [25, 30]])

In [16]:
a.T

array([[ 0, 20],
       [ 5, 25],
       [10, 30]])

swapaxes method that takes a pair of axis numbers and returns a view on the data, without making a copy:

In [19]:
a = np.array([[[0, 1, 2], [3, 4, 5]],
 [[6, 7, 8], [9, 10, 11]]])

In [20]:
a.swapaxes(1, 2)

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])

### Data processing using arrays
- sum
- prod
- diff
- gradient
- cross
- std, var
- mean
- where
- unique

### Loading and saving data

In [21]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.save('test1.npy', a)

we want to store several arrays into a single  le in an uncompressed .npz format

In [23]:
a = np.arange(4)
b = np.arange(7)
np.savez('test2.npz', arr0=a, arr1=b)

In [24]:
dic = np.load('test2.npz')
dic['arr0']

array([0, 1, 2, 3])

### Linear algebra with NumPy